hdl_param -add genom_lngt ga
hdl_param -add score_sz ga
hdl_param -add scaling_factor_res ga
hdl_param -add pop_sz ga
hdl_param -add elite ga
hdl_param -add mr ga
hdl_param -add mut_res ga
hdl_param -add fit_limit ga
hdl_param -add max_gen ga
