@TM:1162398239
@N:  :"":0:0:0:-1|Setting default value for generic score_sz to 8;
@TM:1162397222
@N:  :"":0:0:0:-1|Setting default value for generic genom_lngt to 8;
@N:  :"":0:0:0:-1|Setting default value for generic scaling_factor_res to 4;
@N:  :"":0:0:0:-1|Setting default value for generic pop_sz to 8;
@N:  :"":0:0:0:-1|Setting default value for generic elite to 2;
@N:  :"":0:0:0:-1|Setting default value for generic mr to 150;
@N:  :"":0:0:0:-1|Setting default value for generic mut_res to 8;
@N:  :"":0:0:0:-1|Setting default value for generic fit_limit to 510;
@N:  :"":0:0:0:-1|Setting default value for generic max_gen to 100;
@N:  :"":0:0:0:-1|Using encoding styles selected by FSM Explorer.
@N:  :"":0:0:0:-1|Gated clock conversion enabled 
@TM:1162816782
@W: BN116 :"":0:0:0:-1|Removing sequential instance done_t of view:PrimLib.dffre(prim) because there are no references to its outputs 
@W: BN116 :"":0:0:0:-1|Removing sequential instance cumSum_p1[10:0] of view:PrimLib.dffre(prim) because there are no references to its outputs 
@W: BN116 :"":0:0:0:-1|Removing sequential instance temp_rd of view:PrimLib.dffr(prim) because there are no references to its outputs 
@TM:1162397222
@N: BN191 :"":0:0:0:-1|Writing property annotation file D:\Designs\GA_eval\syn\GA\rev_1\top.tap.
@N: BN225 :"":0:0:0:-1|Writing default property annotation file D:\Designs\GA_eval\syn\GA\rev_1\top.map.
@TM:1162817338
@N: MF197 :"":0:0:0:-1|Retiming summary : 47 registers retimed to 167 
@TM:1162397222
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1162488293
@N: CD630 :"d:\designs\ga_eval\vhd\control_v5.vhd":37:7:37:16|M
@N: CD231 :"d:\designs\ga_eval\vhd\control_v5.vhd":88:17:88:18|M
@TM:1162491564
@N: CL201 :"d:\designs\ga_eval\vhd\control_v5.vhd":149:4:149:5|M
@TM:1162816782
@N:  :"d:\designs\ga_eval\vhd\control_v5.vhd":158:4:158:5|M
@TM:1162491564
@W: CL169 :"d:\designs\ga_eval\vhd\control_v5.vhd":158:4:158:5|M
@N: CL201 :"d:\designs\ga_eval\vhd\control_v5.vhd":158:4:158:5|M
@W: BN116 :"d:\designs\ga_eval\vhd\control_v5.vhd":199:4:199:5|M
@W: BN116 :"d:\designs\ga_eval\vhd\control_v5.vhd":199:4:199:5|M
@TM:1162576458
@N: MF179 :"d:\designs\ga_eval\vhd\control_v5.vhd":207:13:207:49|M
@N: MF179 :"d:\designs\ga_eval\vhd\control_v5.vhd":207:13:207:49|M
@W: BN116 :"d:\designs\ga_eval\vhd\control_v5.vhd":993:4:993:5|M
@W: BN116 :"d:\designs\ga_eval\vhd\control_v5.vhd":993:4:993:5|M
@W: CL111 :"d:\designs\ga_eval\vhd\control_v5.vhd":993:4:993:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\control_v5.vhd":993:4:993:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\control_v5.vhd":993:4:993:5|M
@W: CL189 :"d:\designs\ga_eval\vhd\control_v5.vhd":993:4:993:5|M
@W: CL190 :"d:\designs\ga_eval\vhd\control_v5.vhd":993:4:993:5|M
@W: CL208 :"d:\designs\ga_eval\vhd\control_v5.vhd":993:4:993:5|M
@TM:1162488293
@N: CD630 :"d:\designs\ga_eval\vhd\crossover_v2.vhd":36:7:36:18|M
@TM:1162816782
@W: BN116 :"d:\designs\ga_eval\vhd\crossover_v2.vhd":68:70:68:72|M
@TM:1162397222
@N: CD630 :"d:\designs\ga_eval\vhd\delay_regs.vhd":33:7:33:16|M
@N: CD630 :"d:\designs\ga_eval\vhd\fit_calc.vhd":37:7:37:14|M
@TM:1162488293
@W: CL171 :"d:\designs\ga_eval\vhd\fit_calc.vhd":72:4:72:5|M
@W: CL190 :"d:\designs\ga_eval\vhd\fit_calc.vhd":72:4:72:5|M
@TM:1162397222
@N: CD630 :"d:\designs\ga_eval\vhd\fix_elite.vhd":37:7:37:15|M
@TM:1162488295
@W: BN132 :"d:\designs\ga_eval\vhd\fix_elite.vhd":92:4:92:5|M
@TM:1162488293
@W: CL169 :"d:\designs\ga_eval\vhd\fix_elite.vhd":92:4:92:5|M
@N: CL201 :"d:\designs\ga_eval\vhd\fix_elite.vhd":92:4:92:5|M
@TM:1162817338
@N: FX271 :"d:\designs\ga_eval\vhd\fix_elite.vhd":92:4:92:5|M
@TM:1162397222
@N: CD630 :"d:\designs\ga_eval\vhd\mutation_v2.vhd":37:7:37:17|M
@TM:1162816975
@W: BN116 :"d:\designs\ga_eval\vhd\mutation_v2.vhd":76:4:76:5|M
@TM:1162397222
@N: CD630 :"d:\designs\ga_eval\vhd\obs.vhd":37:7:37:9|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@TM:1162488293
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@TM:1162397222
@N: CD630 :"d:\designs\ga_eval\vhd\selection.vhd":36:7:36:15|M
@TM:1162565457
@W: BN116 :"d:\designs\ga_eval\vhd\selection.vhd":75:4:75:5|M
@W: BN116 :"d:\designs\ga_eval\vhd\selection.vhd":75:4:75:5|M
@W: BN132 :"d:\designs\ga_eval\vhd\selection.vhd":75:4:75:5|M
@N: MF179 :"d:\designs\ga_eval\vhd\selection.vhd":122:35:122:56|M
@TM:1162397222
@N: CD630 :"d:\designs\ga_eval\vhd\spram1.vhd":33:7:33:12|M
@N: CD630 :"d:\designs\ga_eval\vhd\spram1.vhd":33:7:33:12|M
@TM:1162488293
@W: CL209 :"d:\designs\ga_eval\vhd\spram1.vhd":40:4:40:6|M
@W: CL209 :"d:\designs\ga_eval\vhd\spram1.vhd":40:4:40:6|M
@TM:1162488311
@W: BN116 :"d:\designs\ga_eval\vhd\spram1.vhd":68:4:68:5|M
@W: BN116 :"d:\designs\ga_eval\vhd\spram1.vhd":68:4:68:5|M
@TM:1162488302
@W: BN132 :"d:\designs\ga_eval\vhd\spram1.vhd":68:4:68:5|M
@W: BN132 :"d:\designs\ga_eval\vhd\spram1.vhd":68:4:68:5|M
@TM:1162397222
@N: CD630 :"d:\designs\ga_eval\vhd\top.vhd":35:7:35:8|M
@N: CD630 :"d:\designs\ga_eval\vhd\top_fit_eval.vhd":35:7:35:17|M
