@TM:1163618661
@N:  :"":0:0:0:-1|Writing default property annotation file D:\Designs\GA_eval\syn\GA\rev_1\top.map.
@TM:1162818306
@N:  :"":0:0:0:-1|Setting default value for generic elite to 2;
@N:  :"":0:0:0:-1|Setting default value for generic fit_limit to 510;
@N:  :"":0:0:0:-1|Setting default value for generic genom_lngt to 8;
@N:  :"":0:0:0:-1|Setting default value for generic max_gen to 100;
@N:  :"":0:0:0:-1|Setting default value for generic mr to 150;
@N:  :"":0:0:0:-1|Setting default value for generic mut_res to 8;
@N:  :"":0:0:0:-1|Setting default value for generic pop_sz to 8;
@N:  :"":0:0:0:-1|Setting default value for generic scaling_factor_res to 4;
@N:  :"":0:0:0:-1|Setting default value for generic score_sz to 8;
@N:  :"":0:0:0:-1|Using encoding styles selected by FSM Explorer.
@TM:1163618638
@N: MF179 :"":0:0:0:-1|Found 32 bit by 32 bit '==' comparator, 'loop0.un7_dummy_cnt_adapt'
@N: MF179 :"":0:0:0:-1|Found 32 bit by 32 bit '==' comparator, 'loop1.un20_dummy_cnt_adapt'
@TM:1163618635
@N: MF179 :"":0:0:0:-1|Found 15 bit by 15 bit '==' comparator, 'selection.un17_data_valid'
@TM:1163618656
@N: MF197 :"":0:0:0:-1|Retiming summary : 99 registers retimed to 385 
@TM:1162818306
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1163618627
@N:  :"d:\designs\ga_eval\vhd\control_v5.vhd":38:7:38:16|M
@TM:1162818306
@N: CD231 :"d:\designs\ga_eval\vhd\control_v5.vhd":88:17:88:18|M
@N: CL201 :"d:\designs\ga_eval\vhd\control_v5.vhd":149:4:149:5|M
@N:  :"d:\designs\ga_eval\vhd\control_v5.vhd":158:4:158:5|M
@TM:1163618653
@W: BN116 :"d:\designs\ga_eval\vhd\control_v5.vhd":158:4:158:5|M
@TM:1162818306
@N: CL201 :"d:\designs\ga_eval\vhd\control_v5.vhd":158:4:158:5|M
@W: BN116 :"d:\designs\ga_eval\vhd\control_v5.vhd":199:4:199:5|M
@TM:1163618654
@W: BN116 :"d:\designs\ga_eval\vhd\control_v5.vhd":425:6:425:31|M
@TM:1163438639
@W: CL111 :"d:\designs\ga_eval\vhd\control_v5.vhd":991:4:991:5|M
@W: CL208 :"d:\designs\ga_eval\vhd\control_v5.vhd":991:4:991:5|M
@TM:1163618627
@N:  :"d:\designs\ga_eval\vhd\crossover_v2.vhd":36:7:36:18|M
@TM:1163618653
@W: BN116 :"d:\designs\ga_eval\vhd\crossover_v2.vhd":73:4:73:5|M
@TM:1163618627
@N:  :"d:\designs\ga_eval\vhd\delay_regs.vhd":35:7:35:16|M
@N:  :"d:\designs\ga_eval\vhd\fit_calc.vhd":37:7:37:14|M
@TM:1163618653
@W: BN116 :"d:\designs\ga_eval\vhd\fit_calc.vhd":72:4:72:5|M
@TM:1163447394
@W: CL171 :"d:\designs\ga_eval\vhd\fit_calc.vhd":72:4:72:5|M
@W: CL190 :"d:\designs\ga_eval\vhd\fit_calc.vhd":72:4:72:5|M
@TM:1163618627
@N:  :"d:\designs\ga_eval\vhd\fix_elite.vhd":39:7:39:15|M
@TM:1163618656
@W: BN116 :"d:\designs\ga_eval\vhd\fix_elite.vhd":94:4:94:5|M
@TM:1163618632
@W: BN132 :"d:\designs\ga_eval\vhd\fix_elite.vhd":94:4:94:5|M
@TM:1163618627
@W: CL169 :"d:\designs\ga_eval\vhd\fix_elite.vhd":94:4:94:5|M
@N: CL201 :"d:\designs\ga_eval\vhd\fix_elite.vhd":94:4:94:5|M
@TM:1163618655
@N: FX235 :"d:\designs\ga_eval\vhd\fix_elite.vhd":94:4:94:5|M
@TM:1163618656
@N: FX235 :"d:\designs\ga_eval\vhd\fix_elite.vhd":114:6:114:7|M
@TM:1163618627
@N:  :"d:\designs\ga_eval\vhd\mutation_v2.vhd":37:7:37:17|M
@TM:1163447410
@W: BN116 :"d:\designs\ga_eval\vhd\mutation_v2.vhd":76:4:76:5|M
@TM:1163618627
@N:  :"d:\designs\ga_eval\vhd\obs.vhd":38:7:38:9|M
@N:  :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@W:  :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@TM:1163618655
@W: BN116 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@TM:1163447394
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@TM:1163618655
@N: FX235 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@TM:1163618627
@N:  :"d:\designs\ga_eval\vhd\selection.vhd":37:7:37:15|M
@TM:1163447397
@W: BN116 :"d:\designs\ga_eval\vhd\selection.vhd":75:4:75:5|M
@TM:1163618635
@N: FO125 :"d:\designs\ga_eval\vhd\selection.vhd":89:6:89:7|M
@TM:1163447407
@W: BN116 :"d:\designs\ga_eval\vhd\selection.vhd":157:4:157:5|M
@W: BN132 :"d:\designs\ga_eval\vhd\selection.vhd":157:4:157:5|M
@TM:1163618627
@N:  :"d:\designs\ga_eval\vhd\spram1.vhd":37:7:37:12|M
@W:  :"d:\designs\ga_eval\vhd\spram1.vhd":44:4:44:6|M
@TM:1163527442
@N: CL134 :"d:\designs\ga_eval\vhd\spram1.vhd":57:9:57:12|M
@W: BN116 :"d:\designs\ga_eval\vhd\spram1.vhd":69:4:69:5|M
@W: BN132 :"d:\designs\ga_eval\vhd\spram1.vhd":69:4:69:5|M
@W: BN116 :"d:\designs\ga_eval\vhd\spram1.vhd":86:4:86:5|M
@W: CL170 :"d:\designs\ga_eval\vhd\spram1.vhd":86:4:86:5|M
@TM:1163618627
@N:  :"d:\designs\ga_eval\vhd\top.vhd":37:7:37:8|M
@TM:1163618654
@W: BN116 :"d:\designs\ga_eval\vhd\top.vhd":325:2:325:4|M
@TM:1163618627
@N:  :"d:\designs\ga_eval\vhd\top_fit_eval.vhd":37:7:37:17|M
