@TM:1162818306
@N:  :"":0:0:0:-1|Setting default value for generic genom_lngt to 8;
@N:  :"":0:0:0:-1|Setting default value for generic score_sz to 8;
@N:  :"":0:0:0:-1|Setting default value for generic scaling_factor_res to 4;
@N:  :"":0:0:0:-1|Setting default value for generic pop_sz to 8;
@N:  :"":0:0:0:-1|Setting default value for generic elite to 2;
@N:  :"":0:0:0:-1|Setting default value for generic mr to 150;
@N:  :"":0:0:0:-1|Setting default value for generic mut_res to 8;
@N:  :"":0:0:0:-1|Setting default value for generic fit_limit to 510;
@N:  :"":0:0:0:-1|Setting default value for generic max_gen to 100;
@N:  :"":0:0:0:-1|Using encoding styles selected by FSM Explorer.
@N:  :"":0:0:0:-1|Gated clock conversion enabled 
@N: BN191 :"":0:0:0:-1|Writing property annotation file D:\Designs\GA_eval\syn\GA\rev_1\top.tap.
@N: BN225 :"":0:0:0:-1|Writing default property annotation file D:\Designs\GA_eval\syn\GA\rev_1\top.map.
@TM:1163516996
@N: MF197 :"":0:0:0:-1|Retiming summary : 55 registers retimed to 169 
@TM:1162818306
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@N: CD630 :"d:\designs\ga_eval\vhd\control_v5.vhd":37:7:37:16|M
@N: CD231 :"d:\designs\ga_eval\vhd\control_v5.vhd":88:17:88:18|M
@N: CL201 :"d:\designs\ga_eval\vhd\control_v5.vhd":149:4:149:5|M
@N:  :"d:\designs\ga_eval\vhd\control_v5.vhd":158:4:158:5|M
@N: CL201 :"d:\designs\ga_eval\vhd\control_v5.vhd":158:4:158:5|M
@W: BN116 :"d:\designs\ga_eval\vhd\control_v5.vhd":199:4:199:5|M
@N: MF179 :"d:\designs\ga_eval\vhd\control_v5.vhd":207:13:207:49|M
@TM:1163438639
@W: BN116 :"d:\designs\ga_eval\vhd\control_v5.vhd":991:4:991:5|M
@W: BN116 :"d:\designs\ga_eval\vhd\control_v5.vhd":991:4:991:5|M
@W: CL111 :"d:\designs\ga_eval\vhd\control_v5.vhd":991:4:991:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\control_v5.vhd":991:4:991:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\control_v5.vhd":991:4:991:5|M
@W: CL189 :"d:\designs\ga_eval\vhd\control_v5.vhd":991:4:991:5|M
@W: CL190 :"d:\designs\ga_eval\vhd\control_v5.vhd":991:4:991:5|M
@W: CL208 :"d:\designs\ga_eval\vhd\control_v5.vhd":991:4:991:5|M
@TM:1162818306
@N: CD630 :"d:\designs\ga_eval\vhd\crossover_v2.vhd":36:7:36:18|M
@TM:1163448981
@W: BN116 :"d:\designs\ga_eval\vhd\crossover_v2.vhd":68:70:68:72|M
@TM:1162818306
@N: CD630 :"d:\designs\ga_eval\vhd\delay_regs.vhd":33:7:33:16|M
@TM:1163447394
@N: CD630 :"d:\designs\ga_eval\vhd\fit_calc.vhd":37:7:37:14|M
@W: CL171 :"d:\designs\ga_eval\vhd\fit_calc.vhd":72:4:72:5|M
@W: CL190 :"d:\designs\ga_eval\vhd\fit_calc.vhd":72:4:72:5|M
@N: CD630 :"d:\designs\ga_eval\vhd\fix_elite.vhd":37:7:37:15|M
@TM:1163447410
@W: BN116 :"d:\designs\ga_eval\vhd\fix_elite.vhd":92:4:92:5|M
@W: BN116 :"d:\designs\ga_eval\vhd\fix_elite.vhd":92:4:92:5|M
@TM:1163447397
@W: BN132 :"d:\designs\ga_eval\vhd\fix_elite.vhd":92:4:92:5|M
@TM:1163447394
@W: CL169 :"d:\designs\ga_eval\vhd\fix_elite.vhd":92:4:92:5|M
@N: CL201 :"d:\designs\ga_eval\vhd\fix_elite.vhd":92:4:92:5|M
@TM:1163447410
@N: FX271 :"d:\designs\ga_eval\vhd\fix_elite.vhd":112:6:112:7|M
@TM:1163447394
@N: CD630 :"d:\designs\ga_eval\vhd\mutation_v2.vhd":37:7:37:17|M
@TM:1163447410
@W: BN116 :"d:\designs\ga_eval\vhd\mutation_v2.vhd":76:4:76:5|M
@TM:1163447394
@N: CD630 :"d:\designs\ga_eval\vhd\obs.vhd":37:7:37:9|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@TM:1163447405
@N: FA196 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@TM:1163447394
@N: CD630 :"d:\designs\ga_eval\vhd\selection.vhd":37:7:37:15|M
@TM:1163447397
@W: BN116 :"d:\designs\ga_eval\vhd\selection.vhd":75:4:75:5|M
@TM:1163447398
@N: MF179 :"d:\designs\ga_eval\vhd\selection.vhd":123:35:123:56|M
@TM:1163447407
@W: BN116 :"d:\designs\ga_eval\vhd\selection.vhd":157:4:157:5|M
@W: BN132 :"d:\designs\ga_eval\vhd\selection.vhd":157:4:157:5|M
@TM:1163448981
@N: CD630 :"d:\designs\ga_eval\vhd\spram1.vhd":33:7:33:12|M
@N: CD630 :"d:\designs\ga_eval\vhd\spram1.vhd":33:7:33:12|M
@W: CL209 :"d:\designs\ga_eval\vhd\spram1.vhd":40:4:40:6|M
@W: CL209 :"d:\designs\ga_eval\vhd\spram1.vhd":40:4:40:6|M
@TM:1163516996
@W: CL159 :"d:\designs\ga_eval\vhd\spram1.vhd":44:4:44:8|M
@W: CL159 :"d:\designs\ga_eval\vhd\spram1.vhd":44:4:44:8|M
@N: CL134 :"d:\designs\ga_eval\vhd\spram1.vhd":51:9:51:12|M
@N: CL134 :"d:\designs\ga_eval\vhd\spram1.vhd":51:9:51:12|M
@W: BN116 :"d:\designs\ga_eval\vhd\spram1.vhd":64:4:64:5|M
@W: BN132 :"d:\designs\ga_eval\vhd\spram1.vhd":64:4:64:5|M
@W: CL169 :"d:\designs\ga_eval\vhd\spram1.vhd":81:4:81:5|M
@W: CL169 :"d:\designs\ga_eval\vhd\spram1.vhd":81:4:81:5|M
@W: CL170 :"d:\designs\ga_eval\vhd\spram1.vhd":81:4:81:5|M
@W: CL170 :"d:\designs\ga_eval\vhd\spram1.vhd":81:4:81:5|M
@TM:1163448981
@N: CD630 :"d:\designs\ga_eval\vhd\top.vhd":36:7:36:8|M
@N: CD630 :"d:\designs\ga_eval\vhd\top_fit_eval.vhd":36:7:36:17|M
