hdl_param -add genom_lngt ga_tsp
hdl_param -add score_sz ga_tsp
hdl_param -add scaling_factor_res ga_tsp
hdl_param -add pop_sz ga_tsp
hdl_param -add elite ga_tsp
hdl_param -add num_towns ga_tsp
hdl_param -add townres ga_tsp
hdl_param -add mr ga_tsp
hdl_param -add mut_res ga_tsp
hdl_param -add max_gen ga_tsp
