@TM:1162917886
@N:  :"":0:0:0:-1|Using encoding styles selected by FSM Explorer.
@N:  :"":0:0:0:-1|Gated clock conversion enabled 
@N: BN191 :"":0:0:0:-1|Writing property annotation file D:\Designs\GA_eval\syn\GA_TSP\rev_1\top_ga_tsp.tap.
@N: BN225 :"":0:0:0:-1|Writing default property annotation file D:\Designs\GA_eval\syn\GA_TSP\rev_1\top_ga_tsp.map.
@TM:1162925779
@N: MF197 :"":0:0:0:-1|Retiming summary : 143 registers retimed to 380 
@TM:1162917886
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@N: CD630 :"d:\designs\ga_eval\vhd\control_tsp.vhd":20:7:20:17|M
@N: CD231 :"d:\designs\ga_eval\vhd\control_tsp.vhd":64:17:64:18|M
@TM:1162924277
@N: CL201 :"d:\designs\ga_eval\vhd\control_tsp.vhd":123:4:123:5|M
@N:  :"d:\designs\ga_eval\vhd\control_tsp.vhd":132:4:132:5|M
@N:  :"d:\designs\ga_eval\vhd\control_tsp.vhd":132:4:132:5|M
@N:  :"d:\designs\ga_eval\vhd\control_tsp.vhd":132:4:132:5|M
@N:  :"d:\designs\ga_eval\vhd\control_tsp.vhd":132:4:132:5|M
@N: CL201 :"d:\designs\ga_eval\vhd\control_tsp.vhd":132:4:132:5|M
@N: MF179 :"d:\designs\ga_eval\vhd\control_tsp.vhd":180:13:180:46|M
@W: BN116 :"d:\designs\ga_eval\vhd\control_tsp.vhd":910:4:910:5|M
@W: BN116 :"d:\designs\ga_eval\vhd\control_tsp.vhd":910:4:910:5|M
@W: CL111 :"d:\designs\ga_eval\vhd\control_tsp.vhd":910:4:910:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\control_tsp.vhd":910:4:910:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\control_tsp.vhd":910:4:910:5|M
@N: CL177 :"d:\designs\ga_eval\vhd\control_tsp.vhd":910:4:910:5|M
@W: CL189 :"d:\designs\ga_eval\vhd\control_tsp.vhd":910:4:910:5|M
@W: CL190 :"d:\designs\ga_eval\vhd\control_tsp.vhd":910:4:910:5|M
@W: CL208 :"d:\designs\ga_eval\vhd\control_tsp.vhd":910:4:910:5|M
@TM:1162917886
@N: CD630 :"d:\designs\ga_eval\vhd\coordinates_rom_p.vhd":34:7:34:23|M
@N: CD630 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":36:7:36:19|M
@W: CL209 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":44:4:44:14|M
@TM:1162918920
@W: BN116 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@W: CL170 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@W: CL190 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@N: CL201 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@W: CD609 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":140:35:140:51|M
@TM:1162917886
@N: CD630 :"d:\designs\ga_eval\vhd\delay_regs.vhd":33:7:33:16|M
@N: CD630 :"d:\designs\ga_eval\vhd\fitness_calc_tsp.vhd":37:7:37:18|M
@TM:1162920157
@W: BN116 :"d:\designs\ga_eval\vhd\fitness_calc_tsp.vhd":82:4:82:5|M
@TM:1162917886
@N: CD630 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":37:7:37:19|M
@TM:1162920157
@W: BN132 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":96:4:96:5|M
@W: CL169 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":96:4:96:5|M
@N: CL201 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":96:4:96:5|M
@N: FA196 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":117:6:117:7|M
@N: MF179 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":143:53:143:72|M
@TM:1162917886
@N: CD630 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":35:7:35:27|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MF138 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: MO106 :"d:\designs\ga_eval\vhd\init_generation_rom_p.vhd":53:14:53:32|M
@N: CD630 :"d:\designs\ga_eval\vhd\mutation_tsp.vhd":38:7:38:18|M
@TM:1162921769
@W: BN116 :"d:\designs\ga_eval\vhd\mutation_tsp.vhd":70:4:70:5|M
@TM:1162917886
@N: CD630 :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng.vhd":40:7:40:9|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@TM:1162920157
@N: FA196 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@TM:1162925779
@N: FX271 :"d:\designs\ga_eval\vhd\rng.vhd":74:28:74:29|M
@TM:1162917886
@N: CD630 :"d:\designs\ga_eval\vhd\selection.vhd":37:7:37:15|M
@TM:1162921263
@W: BN116 :"d:\designs\ga_eval\vhd\selection.vhd":75:4:75:5|M
@TM:1162917886
@N: FA196 :"d:\designs\ga_eval\vhd\selection.vhd":89:6:89:7|M
@N: MF179 :"d:\designs\ga_eval\vhd\selection.vhd":125:35:125:56|M
@N: CD630 :"d:\designs\ga_eval\vhd\spram1.vhd":33:7:33:12|M
@N: CD630 :"d:\designs\ga_eval\vhd\spram1.vhd":33:7:33:12|M
@W: CL209 :"d:\designs\ga_eval\vhd\spram1.vhd":40:4:40:6|M
@W: CL209 :"d:\designs\ga_eval\vhd\spram1.vhd":40:4:40:6|M
@W: BN116 :"d:\designs\ga_eval\vhd\spram1.vhd":68:4:68:5|M
@W: BN132 :"d:\designs\ga_eval\vhd\spram1.vhd":68:4:68:5|M
@N: CD630 :"d:\designs\ga_eval\vhd\top_fit_eval_tsp.vhd":36:7:36:18|M
@N: CD630 :"d:\designs\ga_eval\vhd\top_ga_tsp.vhd":36:7:36:12|M
