@TM:1164043924
@N:  :"":0:0:0:-1|Gated clock conversion enabled 
@TM:1162917886
@N:  :"":0:0:0:-1|Using encoding styles selected by FSM Explorer.
@TM:1164043924
@N: BN191 :"":0:0:0:-1|Writing property annotation file D:\Designs\GA_eval\syn\GA_TSP\rev_1\top_ga_tsp.tap.
@N: BN225 :"":0:0:0:-1|Writing default property annotation file D:\Designs\GA_eval\syn\GA_TSP\rev_1\top_ga_tsp.map.
@TM:1164048823
@N: MF197 :"":0:0:0:-1|Retiming summary : 140 registers retimed to 353 
@TM:1164043924
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@TM:1162917886
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1164043924
@N: CD630 :"d:\designs\ga_eval\vhd\control_tsp.vhd":32:7:32:17|M
@TM:1164041105
@N: CD231 :"d:\designs\ga_eval\vhd\control_tsp.vhd":75:17:75:18|M
@TM:1164043924
@N: CL201 :"d:\designs\ga_eval\vhd\control_tsp.vhd":128:4:128:5|M
@N:  :"d:\designs\ga_eval\vhd\control_tsp.vhd":137:4:137:5|M
@N: CL201 :"d:\designs\ga_eval\vhd\control_tsp.vhd":137:4:137:5|M
@N: FX271 :"d:\designs\ga_eval\vhd\control_tsp.vhd":137:4:137:5|M
@N: MF179 :"d:\designs\ga_eval\vhd\control_tsp.vhd":185:13:185:46|M
@W: BN116 :"d:\designs\ga_eval\vhd\control_tsp.vhd":894:4:894:5|M
@W: CL111 :"d:\designs\ga_eval\vhd\control_tsp.vhd":894:4:894:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\control_tsp.vhd":894:4:894:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\control_tsp.vhd":894:4:894:5|M
@N: CL177 :"d:\designs\ga_eval\vhd\control_tsp.vhd":894:4:894:5|M
@W: CL189 :"d:\designs\ga_eval\vhd\control_tsp.vhd":894:4:894:5|M
@W: CL208 :"d:\designs\ga_eval\vhd\control_tsp.vhd":894:4:894:5|M
@N: FX271 :"d:\designs\ga_eval\vhd\control_tsp.vhd":894:4:894:5|M
@N: FX271 :"d:\designs\ga_eval\vhd\control_tsp.vhd":894:4:894:5|M
@N: CD630 :"d:\designs\ga_eval\vhd\coordinates_rom.vhd":37:7:37:21|M
@N: CD630 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":37:7:37:19|M
@W: CL209 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":45:4:45:14|M
@W: BN116 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@W: CL170 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@W: CL171 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@W: CL190 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@N: CL201 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@N: FX271 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@N: FX271 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":83:4:83:5|M
@W: CD609 :"d:\designs\ga_eval\vhd\crossover_tsp.vhd":140:35:140:51|M
@N: CD630 :"d:\designs\ga_eval\vhd\delay_regs.vhd":35:7:35:16|M
@N: CD630 :"d:\designs\ga_eval\vhd\fitness_calc_tsp.vhd":39:7:39:22|M
@W: BN116 :"d:\designs\ga_eval\vhd\fitness_calc_tsp.vhd":84:4:84:5|M
@N: CD630 :"d:\designs\ga_eval\vhd\fitness_eval_tsp.vhd":39:7:39:22|M
@N: FX271 :"d:\designs\ga_eval\vhd\fitness_eval_tsp.vhd":84:2:84:3|M
@N: CD630 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":37:7:37:19|M
@W: BN132 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":97:4:97:5|M
@W: CL169 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":97:4:97:5|M
@N: CL201 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":97:4:97:5|M
@N: FA196 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":118:6:118:7|M
@N: MF179 :"d:\designs\ga_eval\vhd\fix_elite_tsp.vhd":144:53:144:72|M
@N: CD630 :"d:\designs\ga_eval\vhd\ga_tsp.vhd":39:7:39:12|M
@N: CD630 :"d:\designs\ga_eval\vhd\init_generation_rom.vhd":37:7:37:25|M
@TM:1164048823
@N: FX271 :"d:\designs\ga_eval\vhd\init_generation_rom.vhd":55:14:55:25|M
@TM:1164043924
@N: CD630 :"d:\designs\ga_eval\vhd\mutation_tsp.vhd":38:7:38:18|M
@TM:1164048823
@W: BN116 :"d:\designs\ga_eval\vhd\mutation_tsp.vhd":70:4:70:5|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng_128.vhd":40:7:40:13|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng_128.vhd":40:7:40:13|M
@N: CD630 :"d:\designs\ga_eval\vhd\rng_128.vhd":40:7:40:13|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL111 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL113 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL170 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL208 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@W: CL212 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@N: FX271 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@N: FX271 :"d:\designs\ga_eval\vhd\rng_128.vhd":72:4:72:5|M
@N: CD630 :"d:\designs\ga_eval\vhd\selection.vhd":38:7:38:15|M
@W: BN116 :"d:\designs\ga_eval\vhd\selection.vhd":80:4:80:5|M
@N: FA196 :"d:\designs\ga_eval\vhd\selection.vhd":93:6:93:7|M
@N: MF179 :"d:\designs\ga_eval\vhd\selection.vhd":127:35:127:56|M
@N: CD630 :"d:\designs\ga_eval\vhd\spram.vhd":38:7:38:11|M
@N: CD630 :"d:\designs\ga_eval\vhd\spram.vhd":38:7:38:11|M
@W: CL209 :"d:\designs\ga_eval\vhd\spram.vhd":46:4:46:6|M
@W: CL209 :"d:\designs\ga_eval\vhd\spram.vhd":46:4:46:6|M
@N: CL134 :"d:\designs\ga_eval\vhd\spram.vhd":65:9:65:12|M
@N: CL134 :"d:\designs\ga_eval\vhd\spram.vhd":65:9:65:12|M
@W: BN116 :"d:\designs\ga_eval\vhd\spram.vhd":77:4:77:5|M
@W: BN132 :"d:\designs\ga_eval\vhd\spram.vhd":77:4:77:5|M
@W: CL170 :"d:\designs\ga_eval\vhd\spram.vhd":94:4:94:5|M
@W: CL170 :"d:\designs\ga_eval\vhd\spram.vhd":94:4:94:5|M
